### PR TITLE
Rename @ViewContainer to @SpringViewDisplay

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring-tutorial/6)

### CODE REVIEW

**Comment by elmot** [comment]
This pull request is only for code comparison. When it is approved, the source branch should be deleted for sake of better branch naming.

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[src/main/java/org/vaadin/spring/tutorial/MyVaadinUI.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/spring-tutorial/6#-KVZHrOj0pm-2PGjOBMr:-KVZHrOj0pm-2PGjOBMs:b6mcdg1) ([raw file](https://github.com/vaadin/spring-tutorial/blob/2e79ccba8ae39bde57b222f5ff260352c17762ec/src/main/java/org/vaadin/spring/tutorial/MyVaadinUI.java#L22)):_

> ``` Java
> public class MyVaadinUI extends UI implements ViewDisplay {
> 
>     private Panel springViewDisplay;
> ```

(does this match the tutorial text?)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring-tutorial/6)_

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[src/main/java/org/vaadin/spring/tutorial/MyUI.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/spring-tutorial/6#-KVZHrOj0pm-2PGjOBMr:-KV_PVXMM7-rWFVj20Kk:b-896fix) ([raw file](https://github.com/vaadin/spring-tutorial/blob/2e79ccba8ae39bde57b222f5ff260352c17762ec/src/main/java/org/vaadin/spring/tutorial/MyUI.java#L22)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> (does this match the tutorial text?)
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring-tutorial/6)_

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring-tutorial/6)_

**Pull request closed without merging**
