### PR TITLE
Rename @ViewContainer to @SpringViewDisplay

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring-tutorial/7)

### CODE REVIEW

**Comment by elmot** [comment]
This pull request is only for code comparison. When it is approved, the source branch should be deleted for sake of better branch naming.

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[src/main/java/org/vaadin/spring/tutorial/MyVaadinUI.java, line 16 at r1](https://reviewable.io:443/reviews/vaadin/spring-tutorial/7#-KVZI4l2EZRIzilD84BV:-KVZI4l3QpFCmomL8kie:b-1b5845) ([raw file](https://github.com/vaadin/spring-tutorial/blob/5100a1f4e86bde711a3db3718ec78b69748503d1/src/main/java/org/vaadin/spring/tutorial/MyVaadinUI.java#L16)):_

> ``` Java
> 
>     @Autowired
>     private ViewPanel springViewDisplay;
> ```

(does this match the tutorial text, if appropriate?)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring-tutorial/7)_

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[src/main/java/org/vaadin/spring/tutorial/MyVaadinUI.java, line 16 at r1](https://reviewable.io:443/reviews/vaadin/spring-tutorial/7#-KVZI4l2EZRIzilD84BV:-KV_PtD449z1Ag-LY1oS:bk9ebls) ([raw file](https://github.com/vaadin/spring-tutorial/blob/5100a1f4e86bde711a3db3718ec78b69748503d1/src/main/java/org/vaadin/spring/tutorial/MyVaadinUI.java#L16)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> (does this match the tutorial text, if appropriate?)
> </details>
> @SpringViewDisplay as a separate class (different form UI)  is not covered by the tutorial.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring-tutorial/7)_

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[src/main/java/org/vaadin/spring/tutorial/MyVaadinUI.java, line 16 at r1](https://reviewable.io:443/reviews/vaadin/spring-tutorial/7#-KVZI4l2EZRIzilD84BV:-KV_QkH1Cc-AHHJx-oTe:bim3soz) ([raw file](https://github.com/vaadin/spring-tutorial/blob/5100a1f4e86bde711a3db3718ec78b69748503d1/src/main/java/org/vaadin/spring/tutorial/MyVaadinUI.java#L16)):_
<details><summary>

<i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>



> @SpringViewDisplay as a separate class (different form UI)  is not covered by the tutorial.
> </details>
> The class is renamed, and the line is equal to a tutorial code example

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring-tutorial/7)_

**Comment by hesara** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring-tutorial/7#-:-KV_RoSkbuT3dJhdTqOh:bnfp4nl)_

**Pull request closed without merging**
